# Generated by Django 5.1.7 on 2025-04-08 19:06

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['cart'], 'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Cart ID'),
        ),
        migrations.AlterField(
            model_name='furnitureassemblyoption',
            name='moving_help_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional charge for moving help.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Moving Help Charge'),
        ),
        migrations.AlterField(
            model_name='furnitureassemblyoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Service Price'),
        ),
        migrations.AlterField(
            model_name='furnitureassemblyoption',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of services requested.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='gazeboserviceoption',
            name='moving_help_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional charge for moving help.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Moving Help Charge'),
        ),
        migrations.AlterField(
            model_name='gazeboserviceoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Service Price'),
        ),
        migrations.AlterField(
            model_name='gazeboserviceoption',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of services requested.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='installationserviceoption',
            name='moving_help_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional charge for moving help.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Moving Help Charge'),
        ),
        migrations.AlterField(
            model_name='installationserviceoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Service Price'),
        ),
        migrations.AlterField(
            model_name='installationserviceoption',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of services requested.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='feature_image',
            field=models.ImageField(blank=True, help_text='A representing image for this category.', null=True, upload_to='service_categories/', verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='tvmountingoption',
            name='moving_help_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional charge for moving help.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Moving Help Charge'),
        ),
        migrations.AlterField(
            model_name='tvmountingoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Service Price'),
        ),
        migrations.AlterField(
            model_name='tvmountingoption',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of services requested.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'content_type', 'object_id')},
        ),
    ]
