# Generated by Django 5.2 on 2025-06-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_order_guest_email_order_guest_name_order_guest_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GazeboModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Model Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gazebo_model_images/', verbose_name='Model Photo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Model Description')),
            ],
            options={
                'verbose_name': 'Gazebo Model',
                'verbose_name_plural': 'Gazebo Models',
            },
        ),
        migrations.AlterField(
            model_name='gazeboserviceoption',
            name='gazebo_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_options', to='services.gazebomodel', verbose_name='Gazebo Model'),
        ),
    ]
